// Chapters 3-20. Loaded before the main script; it calls MORE_CHAPTERS with the item helpers.
window.MORE_CHAPTERS=(I,M,T,B,P)=>{
const PAL=[['#FF7A1A','#FFB31A','#D95F08'],['#10B981','#34D399','#0A9467'],['#1FA2FF','#60C3FF','#0B84DB'],['#FF5470','#FF8FA3','#DE3355'],['#8B5CF6','#B79CFF','#6D3FE0'],['#0FB5AE','#5EEAD4','#0A8A85']];
const ch=(i,title,sub,icon,lessons)=>{const[color,c2,dark]=PAL[i%PAL.length];return{title,sub,icon,color,c2,dark,lessons:[...lessons,{title:'Chapter Review',check:1}]}};
const L=(title,...items)=>({title,items});
return{tags:{save:'Saving vs investing',comp:'Compound interest',bud:'Budgeting',fund:'Funds & ETFs',index:'Index funds',bond:'Bonds',biz:'Reading a business',earn:'Earnings & profit',pe:'Valuation',bullbear:'Bulls & bears',crash:'Crashes & recoveries',feel:'Investor emotions',fee:'Fees & costs',acct:'Accounts',infl:'Inflation',sector:'Sectors',global:'Global markets',scam:'Spotting scams',news:'Reading the news',plan:'Making a plan',dca:'Dollar-cost averaging',rebal:'Rebalancing',crypto:'Crypto basics',goal:'Money goals'},
chapters:[
ch(0,'Save or Invest?','Two ways to grow money','🐷',[
 L('Piggy Bank vs Plant',
  I('Saving','<b>Saving</b> means keeping money safe, like in a piggy bank or bank account. It’s ready when you need it!','🐷'),
  I('Investing','<b>Investing</b> means using money to buy things that can grow, like stocks. It can grow more — but it can also go down.','🌱'),
  M('Which is usually safer for money you need next week?',['🐷|Saving it','🎢|Investing in one stock','🎲|Betting it','🙈|Hiding it in a sock'],0,'Money needed soon should stay safe.','save'),
  T('Investing can grow more than saving over a long time, but it has more risk.',true,'More possible reward usually means more risk.','save'),
  B('Money for next week should be…','kept safe in savings',['invested','gambled'],'save')),
 L('Emergency Fund',
  I('Rainy day money','An <b>emergency fund</b> is savings for surprises — like a broken bike or a vet bill. Grown-ups often save 3–6 months of costs.','☔'),
  M('What is an emergency fund for?',['☔|Unexpected costs','🎮|New video games','📈|Buying hot stocks','🎉|Parties'],0,'It covers surprises so you don’t sell investments at a bad time.','save'),
  T('You should invest your emergency fund in risky stocks.',false,'Emergency money should be easy to get and safe.','save'),
  P([['Piggy bank','Saving'],['Seed','Investing'],['Umbrella','Emergency fund'],['Roller coaster','Risk']],'save'))]),
ch(1,'Compound Magic','Money that grows itself','⛄',[
 L('Interest on Interest',
  I('Interest','When a bank holds your money, it may pay you a little extra called <b>interest</b>.','🏦'),
  I('Compounding','<b>Compound interest</b> means you earn interest on your interest too. $100 at 10% becomes $110, then $121, then $133…','⛄'),
  M('$100 grows 10% a year. After 2 years you have about…',['💵|$121','💵|$120','💵|$200','💵|$102'],0,'Year 1: $110. Year 2: 10% of $110 = $11 more → $121.','comp'),
  T('With compounding, growth gets bigger each year.',true,'The snowball picks up more snow as it rolls.','comp'),
  B('Compounding means earning…','interest on your interest',['loans','taxes'],'comp')),
 L('Start Early',
  I('Time is the secret','Someone who starts at 15 can end up with much more than someone who starts at 35 — even if they save the same each year. Time does the heavy lifting!','⏰'),
  I('Rule of 72','Divide 72 by the growth rate to guess how many years money takes to double. At 8%, 72 ÷ 8 = about <b>9 years</b>.','✌️'),
  M('At 6% growth, about how long until money doubles?',['⏰|12 years','⏰|6 years','⏰|72 years','⏰|2 years'],0,'72 ÷ 6 = 12.','comp'),
  M('What helps compounding the most?',['⏰|Starting early','🏃|Checking prices hourly','🎲|Picking lucky numbers','🛑|Stopping often'],0,'More years = more doubling.','comp'),
  P([['72 ÷ rate','Years to double'],['Snowball','Compounding'],['Interest','Bank’s reward'],['Start early','More time']],'comp'))]),
ch(2,'Budget Boss','Plan where money goes','📒',[
 L('Needs & Wants',
  I('Needs vs wants','<b>Needs</b> are things you must have, like food and a home. <b>Wants</b> are nice extras, like toys and treats.','🍎'),
  M('Which is a NEED?',['🍞|Food','🎮|A new game','🧸|A plush toy','🍬|Candy'],0,'You need food to live.','bud'),
  M('Which is a WANT?',['🎧|Fancy headphones','💧|Water','🏠|A home','🧥|A winter coat'],0,'Headphones are nice, but not required.','bud'),
  T('Spending less than you earn lets you save and invest.',true,'That gap is where wealth starts.','bud')),
 L('The 50/30/20 Rule',
  I('A simple split','One popular budget: <b>50%</b> for needs, <b>30%</b> for wants, <b>20%</b> for saving and investing.','🥧'),
  M('You get $10. With 50/30/20, how much goes to saving?',['💵|$2','💵|$5','💵|$3','💵|$10'],0,'20% of $10 is $2.','bud'),
  B('Pay yourself…','first by saving before spending',['last','never'],'bud'),
  P([['50%','Needs'],['30%','Wants'],['20%','Saving'],['Budget','Money plan']],'bud'))]),
ch(3,'Baskets of Stocks','Mutual funds and ETFs','🧺',[
 L('What’s a Fund?',
  I('Fund','A <b>fund</b> pools money from many people to buy lots of stocks at once. One purchase, many companies!','🧺'),
  I('ETF','An <b>ETF</b> (exchange-traded fund) is a fund you can buy and sell on the stock market, just like a single stock.','🛒'),
  M('What does a fund let you do?',['🧺|Own many companies at once','🎯|Own only one company','🏦|Borrow money','🎟️|Skip all risk'],0,'Funds bundle many investments together.','fund'),
  T('An ETF trades on the stock market like a stock.',true,'That’s the “exchange-traded” part.','fund'),
  B('A fund is a…','basket of many investments',['single','loan'],'fund')),
 L('Fund Flavors',
  I('Many kinds','Some funds hold big companies, some hold tech, some hold companies from other countries. Read the label!','🍦'),
  M('A fund that holds only tech companies is…',['💻|Less diversified','🌍|Very diversified','🏦|A savings account','🧾|A bond'],0,'Holding one industry means less spreading out.','fund'),
  T('All funds are exactly the same.',false,'Funds differ in what they hold and what they cost.','fund'),
  P([['ETF','Trades like a stock'],['Fund','Pooled money'],['Tech fund','One sector'],['Label','What’s inside']],'fund'))]),
ch(4,'Index Funds','Buy the whole market','📊',[
 L('Following an Index',
  I('Index','An <b>index</b> is a list that tracks a group of stocks. The <b>S&amp;P 500</b> follows 500 big U.S. companies.','📋'),
  I('Index fund','An <b>index fund</b> just buys everything in an index. No guessing which stock wins!','📊'),
  M('The S&P 500 tracks about how many companies?',['🔢|500','🔢|5','🔢|50','🔢|5,000'],0,'It’s in the name!','index'),
  T('An index fund tries to match the market, not beat it.',true,'It copies the index.','index'),
  B('An index fund buys…','every stock in the index',['one','random'],'index')),
 L('Why People Love Them',
  I('Cheap and simple','Index funds usually have <b>low fees</b> and are spread across many companies. Many experts suggest them for beginners.','💡'),
  M('Why are index funds popular?',['💡|Low cost and diversified','🎰|Guaranteed big wins','🔒|No risk at all','🚀|Only pick hot stocks'],0,'Low cost + diversification is a winning combo.','index'),
  T('Most professional stock pickers fail to beat the index over long periods.',true,'Studies show most active funds trail the index over time.','index'),
  P([['S&P 500','500 big companies'],['Index','A list of stocks'],['Index fund','Copies the list'],['Low fee','Keeps more money']],'index'))]),
ch(5,'Bonds','Lending money for interest','📜',[
 L('IOUs',
  I('Bond','A <b>bond</b> is a loan you give to a company or government. They promise to pay you back plus interest.','📜'),
  M('When you buy a bond you are…',['🤝|Lending money','🍕|Buying part of a company','🎟️|Buying a ticket','🎁|Giving a gift'],0,'Bonds are loans; stocks are ownership.','bond'),
  T('Bondholders own part of the company.',false,'Bondholders are lenders, not owners.','bond'),
  B('A bond is a…','loan that pays interest',['slice','gift'],'bond')),
 L('Stocks + Bonds',
  I('Steadier ride','Bonds usually move less than stocks. Mixing them can make your investments less bumpy, but grow slower.','⚖️'),
  M('Compared to stocks, bonds are usually…',['⚖️|Steadier, lower growth','🚀|Wilder, higher growth','🎲|Pure luck','🔒|Totally risk-free'],0,'Less bumpy, less growth.','bond'),
  M('Who might hold more bonds?',['👵|Someone retiring soon','👦|A 12-year-old saving for decades','🐶|A puppy','🏎️|A race car'],0,'Near-term needs call for steadier investments.','bond'),
  P([['Bond','Loan'],['Stock','Ownership'],['Interest','Lender’s reward'],['Mix','Smoother ride']],'bond'))]),
ch(0,'Reading a Business','What makes a company good?','🔍',[
 L('Revenue & Profit',
  I('Revenue','<b>Revenue</b> is all the money a company takes in from sales. A lemonade stand selling 10 cups at $1 has $10 revenue.','🍋'),
  I('Profit','<b>Profit</b> is what’s left after paying costs. If lemons and cups cost $6, profit is $4.','💰'),
  M('Revenue $10, costs $6. What’s the profit?',['💰|$4','💰|$16','💰|$10','💰|$6'],0,'$10 − $6 = $4.','biz'),
  T('A company with high revenue is always profitable.',false,'If costs are higher than revenue, it loses money.','biz'),
  B('Profit equals…','revenue minus costs',['plus','times'],'biz')),
 L('Moats',
  I('A castle moat','A <b>moat</b> is something that protects a business from rivals — a famous brand, a secret recipe, or lots of loyal users.','🏰'),
  M('Which is an example of a moat?',['🏰|A brand everyone loves','📉|Falling sales','🧾|Big debts','🚪|Easy for anyone to copy'],0,'Strong brands keep customers coming back.','biz'),
  T('A business that’s easy to copy has a strong moat.',false,'Easy to copy = weak moat.','biz'),
  P([['Revenue','Money in'],['Costs','Money out'],['Profit','What’s left'],['Moat','Protection from rivals']],'biz'))]),
ch(1,'Earnings Season','How companies report results','📣',[
 L('Report Cards',
  I('Earnings report','Every 3 months (a <b>quarter</b>), public companies share a report card on sales and profits called an <b>earnings report</b>.','📣'),
  M('How often do public companies usually report earnings?',['📅|Every 3 months','📅|Every day','📅|Every 10 years','📅|Never'],0,'Four quarters per year.','earn'),
  T('A stock can drop even if the company made a profit.',true,'If profit was lower than people expected, the price can fall.','earn'),
  B('Earnings reports come out every…','quarter of the year',['minute','decade'],'earn')),
 L('Expectations',
  I('Beat or miss','Investors guess earnings ahead of time. Doing better is a <b>beat</b>; doing worse is a <b>miss</b>.','🎯'),
  M('A company earns more than expected. That’s called a…',['🎯|Beat','❌|Miss','🧊|Freeze','🔁|Split'],0,'Beating expectations often lifts the price.','earn'),
  M('EPS stands for…',['🧮|Earnings per share','🧮|Extra price score','🧮|Every person’s stock','🧮|Easy profit system'],0,'Profit divided by number of shares.','earn'),
  P([['Quarter','3 months'],['Beat','Better than expected'],['Miss','Worse than expected'],['EPS','Profit per share']],'earn'))]),
ch(2,'Is It Pricey?','Valuation basics','🏷️',[
 L('P/E Ratio',
  I('Price vs earnings','The <b>P/E ratio</b> compares a stock’s price to its earnings per share. Price $20, EPS $2 → P/E of 10.','🏷️'),
  M('Price $30, EPS $3. What’s the P/E?',['🧮|10','🧮|90','🧮|33','🧮|3'],0,'30 ÷ 3 = 10.','pe'),
  T('A high P/E means investors expect lots of future growth.',true,'People pay more today for expected growth.','pe'),
  B('P/E compares price to…','earnings per share',['weather','employees'],'pe')),
 L('Price ≠ Value',
  I('Cheap or good?','A $5 stock isn’t automatically cheaper than a $500 stock. What matters is how much business you get for the price.','💎'),
  M('Stock A costs $5, Stock B costs $500. Which is the better deal?',['🤔|It depends on the business','5️⃣|Always A','💯|Always B','🎲|Flip a coin'],0,'Share price alone tells you nothing about value.','pe'),
  T('Market cap = share price × number of shares.',true,'That’s the total value of the company.','pe'),
  P([['P/E','Price ÷ EPS'],['Market cap','Total company value'],['High P/E','Growth hopes'],['Value','What you really get']],'pe'))]),
ch(3,'Bulls & Bears','Up markets and down markets','🐻',[
 L('Animal Markets',
  I('Bull market','A <b>bull market</b> is when prices rise for a long time. Bulls charge upward with their horns! 🐂','🐂'),
  I('Bear market','A <b>bear market</b> is when prices fall 20% or more. Bears swipe downward with their paws! 🐻','🐻'),
  M('Prices fall 25% over months. That’s a…',['🐻|Bear market','🐂|Bull market','🐬|Dolphin market','🦄|Unicorn market'],0,'A drop of 20%+ is a bear market.','bullbear'),
  T('Bull markets have historically lasted longer than bear markets.',true,'On average, bulls run longer than bears.','bullbear'),
  B('A bull market means prices go…','up for a long time',['down','sideways'],'bullbear')),
 L('Corrections',
  I('Correction','A drop of 10–20% is called a <b>correction</b>. They happen often — roughly every year or two.','📉'),
  M('A 12% drop is called a…',['📉|Correction','🐻|Bear market','💥|Explosion','🎉|Celebration'],0,'10–20% = correction.','bullbear'),
  P([['🐂 Bull','Rising prices'],['🐻 Bear','Falling 20%+'],['Correction','10–20% drop'],['Rally','Quick rise']],'bullbear'))]),
ch(4,'Crashes & Comebacks','Staying calm in storms','🌪️',[
 L('History Lessons',
  I('Crashes happen','Markets crashed in 1929, 1987, 2008 and 2020. Each time, it was scary — and each time, the U.S. market eventually recovered.','🌪️'),
  M('After past big crashes, the U.S. market has…',['🌈|Eventually recovered','💀|Never come back','🔒|Closed forever','🎲|Been random'],0,'Recovery took time, but it came.','crash'),
  T('Past results guarantee future results.',false,'History helps, but nothing is guaranteed.','crash'),
  B('Crashes are scary but…','markets have recovered before',['never','always'],'crash')),
 L('Don’t Miss the Best Days',
  I('Timing is hard','Some of the market’s best days come right after its worst ones. Selling in a panic can mean missing the bounce.','📈'),
  M('What’s a common mistake in a crash?',['😱|Panic selling','🧘|Staying the course','📚|Learning more','📅|Sticking to a plan'],0,'Selling low locks in losses.','crash'),
  P([['2008','Financial crisis'],['2020','Pandemic drop'],['Recovery','Prices come back'],['Panic sell','Locking in losses']],'crash'))]),
ch(5,'Mind Games','Your brain vs your money','🧠',[
 L('Fear & Greed',
  I('Two big feelings','<b>Fear</b> makes people sell when prices fall. <b>Greed</b> makes people buy when prices are hot. Both can cause mistakes.','🎭'),
  M('Everyone is buying a hot stock. You feel you must too. That’s…',['🤑|FOMO / greed','🧘|Patience','📚|Research','🛡️|Diversifying'],0,'FOMO = fear of missing out.','feel'),
  T('Making money decisions while emotional is usually smart.',false,'Calm decisions beat emotional ones.','feel'),
  B('Be fearful when others are…','greedy and greedy when others are fearful',['sleepy','hungry'],'feel')),
 L('Brain Traps',
  I('Herd behavior','Following the crowd feels safe, but crowds can be wrong. Think for yourself!','🐑'),
  I('Loss aversion','Losing $10 feels about twice as bad as winning $10 feels good. That can make people too scared to invest.','⚖️'),
  M('Following the crowd without thinking is called…',['🐑|Herd behavior','🦁|Leadership','🔬|Analysis','🧭|Planning'],0,'Baa-d idea sometimes!','feel'),
  P([['FOMO','Fear of missing out'],['Herd','Following the crowd'],['Loss aversion','Losses hurt more'],['Greed','Wanting too much']],'feel'))]),
ch(0,'Fees Matter','Small costs, big impact','🧾',[
 L('Expense Ratios',
  I('Expense ratio','Funds charge a yearly fee called the <b>expense ratio</b>. 1% means $1 for every $100 invested, every year.','🧾'),
  M('You invest $1,000 in a fund with a 0.5% fee. Yearly cost?',['💵|$5','💵|$50','💵|$0.50','💵|$500'],0,'0.5% of $1,000 is $5.','fee'),
  T('Over decades, a 1% fee can eat a big chunk of your money.',true,'Fees compound too — in the wrong direction.','fee'),
  B('Lower fees mean you…','keep more of your money',['lose','borrow'],'fee')),
 L('Trading Costs',
  I('Trading too much','Buying and selling a lot can cost fees and taxes. Often, doing less beats doing more!','🔁'),
  M('Which usually keeps costs lower?',['🐢|Buying and holding','🐇|Trading every day','🎰|Chasing tips','🔁|Flipping stocks hourly'],0,'Less trading, fewer costs.','fee'),
  P([['Expense ratio','Yearly fund fee'],['0.03%','Very cheap'],['2%','Expensive'],['Trading','Can add costs']],'fee'))]),
ch(1,'Investing Accounts','Where investments live','🗂️',[
 L('Brokerages',
  I('Brokerage account','To buy stocks you need a <b>brokerage account</b>. Kids usually need a grown-up to open a <b>custodial account</b> for them.','🗂️'),
  M('A grown-up opens an investing account for a kid. It’s called…',['🧒|Custodial account','🏦|Piggy bank','📜|Bond','🎟️|Gift card'],0,'The adult manages it until the kid is older.','acct'),
  T('Anyone of any age can open a brokerage account alone.',false,'Minors usually need an adult custodian.','acct'),
  B('To buy stocks you need a…','brokerage account to trade',['library','passport'],'acct')),
 L('Retirement Accounts',
  I('Tax helpers','Accounts like a <b>401(k)</b> or <b>IRA</b> give tax breaks for saving toward retirement. Some employers even add free money!','🎁'),
  M('An employer “match” is…',['🎁|Free money added to your savings','🧾|A fee','🔥|A penalty','🎮|A game'],0,'It’s like a bonus for saving.','acct'),
  P([['Brokerage','Buy & sell stocks'],['Custodial','Adult-run kid account'],['IRA','Retirement account'],['Match','Free employer money']],'acct'))]),
ch(2,'Inflation','Why prices creep up','🎈',[
 L('Shrinking Dollars',
  I('Inflation','<b>Inflation</b> is when prices rise over time. A candy bar that cost $1 might cost $1.50 years later.','🎈'),
  M('Inflation makes each dollar buy…',['📉|Less','📈|More','➖|The same','🎁|Double'],0,'Rising prices shrink buying power.','infl'),
  T('Cash under a mattress loses buying power to inflation.',true,'It stays the same number but buys less.','infl'),
  B('Inflation means prices…','rise over time',['vanish','freeze'],'infl')),
 L('Beating Inflation',
  I('Grow faster','To keep up, your money needs to grow faster than inflation. Over long periods, stocks have usually done that.','🏃'),
  M('Inflation is 3%. Your savings earn 1%. You are…',['📉|Losing buying power','📈|Getting richer','➖|Breaking even','🎉|Winning big'],0,'1% − 3% = −2% in real terms.','infl'),
  P([['Inflation','Rising prices'],['Buying power','What $1 buys'],['Real return','Growth minus inflation'],['Cash','Loses value slowly']],'infl'))]),
ch(3,'Sectors & the World','Spreading across industries & countries','🌍',[
 L('Sectors',
  I('Industries','Stocks are grouped into <b>sectors</b> — like technology, healthcare, energy and consumer goods.','🏭'),
  M('A drug company belongs to which sector?',['🏥|Healthcare','⚡|Energy','💻|Technology','🏦|Banking'],0,'Medicine = healthcare.','sector'),
  T('Owning stocks in many sectors is a form of diversification.',true,'If one industry struggles, others may not.','sector'),
  P([['Apple','Technology'],['Exxon','Energy'],['Pfizer','Healthcare'],['Coca-Cola','Consumer goods']],'sector')),
 L('Going Global',
  I('Worldwide','There are great companies all over the world — Japan, Germany, India and more. International funds let you own them.','🌍'),
  M('Why invest internationally?',['🌍|Spread risk across countries','🎲|It’s guaranteed to win','🛂|You need a passport','🙈|No reason'],0,'Different countries grow at different times.','global'),
  B('Global investing spreads…','risk across many countries',['jam','rumors'],'global'))]),
ch(4,'Scam Spotter','Protect your money','🕵️',[
 L('Red Flags',
  I('Too good to be true','Promises of “guaranteed” huge returns, pressure to act NOW, or secret tips are big <b>red flags</b>.','🚩'),
  M('Someone online promises to double your money in a week, guaranteed. You should…',['🚩|Walk away — it’s a scam','💸|Send money fast','🤫|Keep it secret','📣|Tell them your password'],0,'Real investing never guarantees quick riches.','scam'),
  T('Legit investments can guarantee high returns with no risk.',false,'Return and risk always go together.','scam'),
  B('If it sounds too good to be true…','it probably is a scam',['always','never'],'scam')),
 L('Pump & Dump',
  I('Pump and dump','Scammers hype a tiny stock (pump), then sell when others buy in (dump), leaving everyone else with losses.','🎈'),
  M('A random account hypes a tiny stock “going to the moon”. Likely…',['🎈|A pump and dump','🚀|Free money','📊|An index fund','🏦|A bond'],0,'Hype from strangers is a warning sign.','scam'),
  P([['Guaranteed','Red flag'],['Act now!','Pressure tactic'],['Pump & dump','Hype then sell'],['Password','Never share']],'scam'))]),
ch(5,'Smart Strategies','Simple habits that work','🗓️',[
 L('Dollar-Cost Averaging',
  I('Little and often','<b>Dollar-cost averaging</b> means investing the same amount on a schedule — like $10 every month — no matter the price.','🗓️'),
  M('With DCA, when prices are low your $10 buys…',['➕|More shares','➖|Fewer shares','0️⃣|Nothing','➗|Half a share always'],0,'Same money, lower price → more shares.','dca'),
  T('DCA removes the stress of guessing the perfect time to buy.',true,'You just stick to the schedule.','dca'),
  B('DCA means investing the same amount…','on a regular schedule',['randomly','once'],'dca')),
 L('Rebalancing',
  I('Back to the plan','If you planned 80% stocks and 20% bonds, a big stock rally might make it 90/10. <b>Rebalancing</b> brings it back.','⚖️'),
  M('Your plan is 70/30 but it’s now 85/15. You should…',['⚖️|Rebalance back to 70/30','🙈|Ignore it forever','🎲|Go 100% stocks','🧨|Sell everything'],0,'Rebalancing keeps risk where you want it.','rebal'),
  P([['DCA','Same amount, regularly'],['Rebalance','Return to plan'],['Buy & hold','Patience'],['Plan','Your rules']],'rebal'))]),
ch(0,'Crypto & New Stuff','Hype vs reality','🪙',[
 L('What’s Crypto?',
  I('Digital coins','<b>Cryptocurrency</b> like Bitcoin is digital money that lives on a computer network called a <b>blockchain</b>.','🪙'),
  M('Crypto prices are usually…',['🎢|Very volatile','🐢|Super steady','🔒|Guaranteed','🏦|Insured like a bank'],0,'Crypto can swing wildly in a day.','crypto'),
  T('Crypto is backed by company profits like stocks are.',false,'Coins don’t earn profits like businesses do.','crypto'),
  B('Crypto is very…','risky and volatile',['boring','safe'],'crypto')),
 L('Handle With Care',
  I('Only what you can lose','If people invest in very risky things, a good rule is to only use money they can afford to lose completely.','⚠️'),
  M('A smart approach to very risky investments is…',['⚠️|Only a small amount','💯|Everything you own','🏠|Selling your house','🤝|Borrowing a lot'],0,'Keep risky bets small.','crypto'),
  P([['Bitcoin','Crypto coin'],['Blockchain','Shared ledger'],['Volatile','Big swings'],['Small bets','Limit risk']],'crypto'))]),
ch(1,'Your Money Plan','Put it all together','🏁',[
 L('Set Goals',
  I('SMART goals','Good goals are <b>specific</b> and have a <b>deadline</b>: “Save $200 for a bike by June” beats “save money”.','🎯'),
  M('Which is the best money goal?',['🎯|Save $200 for a bike by June','🤷|Get rich someday','💭|Have more money','🎲|Win the lottery'],0,'Specific + deadline = SMART.','goal'),
  T('Short-term goals and long-term goals can use different strategies.',true,'Soon = save. Far away = invest.','goal'),
  B('A good goal has a…','specific amount and deadline',['secret','wish'],'goal')),
 L('Your Playbook',
  I('The recipe','Spend less than you earn, keep an emergency fund, invest regularly in diversified low-cost funds, and stay patient. That’s it!','📖'),
  M('Which is NOT part of a solid plan?',['🎰|Chasing hot tips','🐷|Emergency fund','📊|Low-cost index funds','🐢|Patience'],0,'Tips and hype aren’t a plan.','plan'),
  M('The most powerful ingredient for long-term investors is…',['⏰|Time','🍀|Luck','📱|Checking the app hourly','🗞️|Gossip'],0,'Time lets compounding work.','plan'),
  P([['Budget','Spend less'],['Emergency fund','Safety net'],['Index fund','Diversify cheaply'],['Patience','Let it grow']],'plan'))])]};
};
